// let c=71;
// c++;
// c++;
// console.log(c);
// c++;
// console.log(c);
// let c=191;
// c--;
// c--;
// console.log(c);
// c--;
// console.log(c);
// let c=71;
// ++c;
// ++c;
// console.log(c);
// ++c;
// console.log(c);
// let a=30;
// z=a++;
// console.log(a);
// console.log(z);
//  let a=30;
// z=++a;
// console.log(a);
// console.log(z);
// let a=30;
// z=a--;
// console.log(a);
// console.log(z);
let a=30;
z=--a;
console.log(a);
console.log(z);